package vnpt.vsp.module.round;

import jakarta.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import vnpt.vsp.api.idempotency.Idempotent;
import vnpt.vsp.module.course.dto.PageResponse;
import vnpt.vsp.module.round.dto.RoundCompleteRequest;
import vnpt.vsp.module.round.dto.RoundCreateRequest;
import vnpt.vsp.module.round.dto.RoundResponse;
import vnpt.vsp.module.score.ScoreService;
import vnpt.vsp.module.score.dto.ScoreCorrectionRequest;
import vnpt.vsp.module.score.dto.ScoreCorrectionResponse;
import vnpt.vsp.module.tournament.TournamentPolicyService;
import vnpt.vsp.module.tournament.dto.TournamentPolicyResponse;

import java.util.UUID;

/**
 * REST controller for round endpoints.
 * Per Story 5.1 Slice D: round creation with idempotency and audit.
 * Per Story 5.5: round completion and score corrections.
 * Per Story 7.4: tournament policy attachment and auto-lock.
 */
@RestController
@RequestMapping("/rounds")
@vnpt.vsp.module.round.RoundModule
public class RoundController {

    private static final Logger log = LoggerFactory.getLogger(RoundController.class);

    private final RoundService roundService;
    private final ScoreService scoreService;
    private final TournamentPolicyService tournamentPolicyService;

    public RoundController(RoundService roundService, ScoreService scoreService,
                          TournamentPolicyService tournamentPolicyService) {
        this.roundService = roundService;
        this.scoreService = scoreService;
        this.tournamentPolicyService = tournamentPolicyService;
    }

    /**
     * Create a new round.
     *
     * Requires Idempotency-Key header for safe retry semantics.
     * The idempotency key should be a unique value generated by the client
     * (e.g. UUID) that identifies this specific round creation request.
     *
     * Per Story 5.1 Slice D:
     * - Validates courseId exists
     * - Validates all playerIds correspond to existing golfer accounts
     * - Creates round with status IN_PROGRESS
     * - Creates score records for each player
     * - Audit logs the round creation
     * Per Story 7.4:
     * - Accepts optional tournamentPolicyId for tournament-format rounds
     * - Auto-locks the policy when round starts
     *
     * @param authentication the authenticated golfer
     * @param request        the round creation request
     * @return the created round with 201 status
     */
    @PostMapping
    @Idempotent(ttlSeconds = 86400) // 24-hour idempotency window
    public ResponseEntity<RoundResponse> createRound(
            Authentication authentication,
            @Valid @RequestBody RoundCreateRequest request) {

        Long accountId = (Long) authentication.getPrincipal();
        log.info("POST /rounds - accountId={}, courseId={}", accountId, request.getCourseId());

        RoundResponse response = roundService.createRound(accountId, request);

        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    /**
     * List the authenticated golfer's rounds, most recent first, paginated.
     *
     * Used by the mobile app to sync round history for the signed-in golfer.
     * Returns a standard PageResponse wrapper (content, page, size, totalElements,
     * totalPages, first, last).
     *
     * @param authentication the authenticated golfer
     * @param page           zero-based page index (default 0)
     * @param size           page size (default 20, max 100)
     * @return 200 with a paginated page of the golfer's rounds
     */
    @GetMapping
    public ResponseEntity<PageResponse<RoundResponse>> listRounds(
            Authentication authentication,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "20") int size) {

        Long accountId = (Long) authentication.getPrincipal();
        log.info("GET /rounds - accountId={}, page={}, size={}", accountId, page, size);

        PageResponse<RoundResponse> response = roundService.listRounds(accountId, page, size);

        return ResponseEntity.ok(response);
    }

    /**
     * Complete a round — marks it as COMPLETED and sets endedAt.
     *
     * Idempotent: if the round is already COMPLETED, returns 200 with the existing round.
     * Validates that the round exists, belongs to the authenticated golfer, and is in IN_PROGRESS status.
     * Per Story 5.5 Slice 1.
     *
     * @param authentication the authenticated golfer
     * @param roundId       the round UUID
     * @return the completed round with 200 status (or 201 if newly completed)
     */
    @PostMapping("/{roundId}/complete")
    @Idempotent(ttlSeconds = 86400)
    public ResponseEntity<RoundResponse> completeRound(
            Authentication authentication,
            @PathVariable UUID roundId,
            @Valid @RequestBody(required = false) RoundCompleteRequest request) {

        Long accountId = (Long) authentication.getPrincipal();
        log.info("POST /rounds/{}/complete - accountId={}", roundId, accountId);

        RoundResponse response = roundService.completeRound(accountId, roundId, request);

        return ResponseEntity.ok(response);
    }

    /**
     * Get the tournament policy for a round.
     *
     * Returns the tournament policy attached to a tournament-format round.
     * This endpoint is used by the mobile app to check feature restrictions.
     * Per Story 7.4 Slice E.
     *
     * @param authentication the authenticated golfer
     * @param roundId      the round UUID
     * @return 200 with the tournament policy, or 404 if the round has no policy
     */
    @GetMapping("/{roundId}/tournament-policy")
    public ResponseEntity<TournamentPolicyResponse> getRoundTournamentPolicy(
            Authentication authentication,
            @PathVariable UUID roundId) {

        Long accountId = (Long) authentication.getPrincipal();
        log.info("GET /rounds/{}/tournament-policy - accountId={}", roundId, accountId);

        TournamentPolicyResponse response = roundService.getRoundTournamentPolicy(roundId, accountId);

        return ResponseEntity.ok(response);
    }

    /**
     * Apply score corrections to a completed round.
     *
     * Validates:
     * - Round exists and belongs to the authenticated golfer
     * - Round status is COMPLETED
     * - All correction fields are in the permitted list (strokes, putts, penalties,
     *   fairwayHit, gir, bunker, notes)
     *
     * Creates audit entries for each correction.
     * Per Story 5.5 Slice 4: score correction with audit trail.
     *
     * @param authentication the authenticated golfer
     * @param roundId        the round UUID
     * @param request        the correction request
     * @return correction response with correctionId, appliedAt, and auditId
     */
    @PostMapping("/{roundId}/corrections")
    @Idempotent(ttlSeconds = 86400)
    public ResponseEntity<ScoreCorrectionResponse> correctScores(
            Authentication authentication,
            @PathVariable UUID roundId,
            @Valid @RequestBody ScoreCorrectionRequest request) {

        Long accountId = (Long) authentication.getPrincipal();
        log.info("POST /rounds/{}/corrections - accountId={}, playerId={}, corrections={}",
                roundId, accountId, request.getPlayerId(),
                request.getCorrections() != null ? request.getCorrections().size() : 0);

        ScoreCorrectionResponse response =
                scoreService.correctScoreEntries(roundId, accountId, request);

        return ResponseEntity.ok(response);
    }
}
