package vnpt.vsp.module.audit;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.*;

/**
 * The dev seed's {@code audit_entries_action_check} must list exactly the
 * constants of {@link AuditAction}.
 *
 * <p>The constraint is generated by Hibernate from the enum, but only when it
 * creates the column; dev runs {@code ddl-auto: update}, which never revises a
 * check constraint afterwards. So on this database it still listed the values
 * of the day it was created and rejected ROUND_ABANDON, CORRECTION_SUBMITTED
 * and CORRECTION_CORROBORATED — while the audit write, being {@code @Async} and
 * catching its own failures, reported nothing to anyone.</p>
 *
 * <p>The seed reissues the constraint on every boot, which fixes existing
 * databases, but only by hard-coding the list — the same list that drifted
 * once. This test is what stops it drifting again: adding a value to the enum
 * without adding it to the seed fails the build, here, rather than a year
 * later as a missing compliance record.</p>
 */
class AuditActionConstraintTest {

    private static final String SEED = "db/seed/dev-seed.sql";

    private static final Pattern CONSTRAINT = Pattern.compile(
            "ADD CONSTRAINT audit_entries_action_check CHECK \\(action IN \\((.*?)\\)\\)",
            Pattern.DOTALL);

    private String seed() throws IOException {
        return new String(new ClassPathResource(SEED).getInputStream().readAllBytes(), StandardCharsets.UTF_8);
    }

    private List<String> constrainedValues() throws IOException {
        Matcher matcher = CONSTRAINT.matcher(seed());
        assertTrue(matcher.find(),
                SEED + " no longer reissues audit_entries_action_check — an old dev database "
                        + "will silently drop audit rows again");
        return Arrays.stream(matcher.group(1).split(","))
                .map(value -> value.trim().replace("'", ""))
                .filter(value -> !value.isEmpty())
                .toList();
    }

    @Test
    @DisplayName("Every AuditAction constant is accepted by the constraint")
    void everyActionIsAccepted() throws IOException {
        List<String> constrained = constrainedValues();
        List<String> missing = Arrays.stream(AuditAction.values())
                .map(Enum::name)
                .filter(name -> !constrained.contains(name))
                .toList();

        assertTrue(missing.isEmpty(),
                "AuditAction has values the dev seed's check constraint rejects, so writing them "
                        + "will lose the audit entry: " + missing + " — add them to " + SEED);
    }

    @Test
    @DisplayName("The constraint lists nothing the enum does not define")
    void noStaleValuesRemain() throws IOException {
        List<String> defined = Arrays.stream(AuditAction.values()).map(Enum::name).toList();
        List<String> unknown = constrainedValues().stream()
                .filter(value -> !defined.contains(value))
                .toList();

        assertTrue(unknown.isEmpty(),
                "The dev seed's check constraint allows values AuditAction no longer defines: " + unknown);
    }

    @Test
    @DisplayName("The constraint is dropped before it is added, so the seed can run twice")
    void theSeedIsIdempotent() throws IOException {
        assertTrue(seed().contains("DROP CONSTRAINT IF EXISTS audit_entries_action_check"),
                "Without the drop, the second boot fails on a duplicate constraint and the rest "
                        + "of the seed never runs");
    }
}
