package vnpt.vsp.module.score;

import jakarta.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import vnpt.vsp.api.idempotency.Idempotent;
import vnpt.vsp.module.score.dto.ScoreCorrectionRequest;
import vnpt.vsp.module.score.dto.ScoreCorrectionResponse;
import vnpt.vsp.module.score.dto.ScoreSyncRequest;
import vnpt.vsp.module.score.dto.ScoreSyncResponse;
import vnpt.vsp.module.score.dto.SyncStatusResponse;

import java.util.UUID;

/**
 * REST controller for score sync endpoints.
 *
 * <p>Per Story 5.4 AC1/AC2:
 * <ul>
 *   <li>All score write endpoints require {@code Idempotency-Key} header.</li>
 *   <li>The {@link IdempotencyFilter} deduplicates repeated submissions within the TTL window.</li>
 *   <li>A {@link SyncStatusResponse} is returned so clients can confirm sync outcome.</li>
 * </ul>
 *
 * <p>The {@code Idempotency-Key} header value must be a UUID v4 generated by the
 * client before queueing the event locally. The same key is reused on retry.
 *
 * <p>TTL: 86400 s (24 hours) — matches architecture §8.3 conservative window.
 */
@RestController
@RequestMapping("/scores")
@vnpt.vsp.module.score.ScoreModule
public class ScoreController {

    private static final Logger log = LoggerFactory.getLogger(ScoreController.class);

    private final ScoreService scoreService;

    public ScoreController(ScoreService scoreService) {
        this.scoreService = scoreService;
    }

    /**
     * Sync a batch of score updates to the server.
     *
     * <p>This endpoint is idempotent: submitting the same {@code Idempotency-Key}
     * multiple times returns the cached response without re-processing.
     *
     * <p>On success (2xx) the client should mark the local event as {@code synced}.
     * On {@code X-Idempotent-Replay: true} the client should also mark {@code synced}
     * (the server deduplicated, not rejected).
     * On 4xx the event is permanently failed — no further retry.
     * On 5xx or network error the event should be re-queued with backoff.
     *
     * @param authentication the authenticated golfer
     * @param idempotencyKey the {@code Idempotency-Key} header (required; causes 400 if absent)
     * @param request        the score sync payload
     * @return sync confirmation with eventId, status, syncedAt, and optionally error
     */
    @PostMapping("/sync")
    @Idempotent(ttlSeconds = 86400)
    public ResponseEntity<SyncStatusResponse> syncScores(
            Authentication authentication,
            @RequestHeader("Idempotency-Key") String idempotencyKey,
            @RequestBody ScoreSyncRequest request) {

        Long accountId = (Long) authentication.getPrincipal();
        log.info("POST /scores/sync – accountId={}, idempotencyKey={}, eventCount={}",
                accountId, idempotencyKey, request.scores() != null ? request.scores().size() : 0);

        SyncStatusResponse response = scoreService.syncScores(accountId, idempotencyKey, request);

        return switch (response.getStatus()) {
            case SYNCED -> ResponseEntity.ok(response);
            case FAILED -> ResponseEntity.internalServerError().body(response);
        };
    }

    /**
     * Submit score corrections for a completed round.
     *
     * <p>Validates that:
     * <ul>
     *   <li>The round is COMPLETED</li>
     *   <li>The corrections target permitted fields only</li>
     *   <li>An audit entry is created for each field change</li>
     * </ul>
     * Per Story 5.5 Slice 4.
     *
     * @param authentication the authenticated golfer
     * @param roundId       the round UUID
     * @param request       the correction request
     * @return correction confirmation with correctionId and auditId
     */
    @PostMapping("/rounds/{roundId}/corrections")
    @Idempotent(ttlSeconds = 86400)
    public ResponseEntity<ScoreCorrectionResponse> submitCorrections(
            Authentication authentication,
            @PathVariable UUID roundId,
            @Valid @RequestBody ScoreCorrectionRequest request) {

        Long accountId = (Long) authentication.getPrincipal();
        log.info("POST /scores/rounds/{}/corrections – accountId={}", roundId, accountId);

        ScoreCorrectionResponse response =
                scoreService.correctScoreEntries(roundId, accountId, request);

        return ResponseEntity.ok(response);
    }
}
