// Not Surveyed Chip — VSP Mobile App
//
// A small amber marker that sits next to a distance whose coordinates nobody
// verified.
//
// It exists because the numbers and their provenance had drifted apart. The
// measuring tool has always been careful — every leg carries a ±, and the
// green note says in words whether the green position is surveyed or
// estimated. The *stated* numbers had none of that: the hole list, the hole
// header and the round's hole context each printed a bare "362m" that came,
// for most holes in the database, from coordinates generated by arithmetic.
//
// Same wording and same amber as the "Not surveyed" badge on the hole map, so
// a golfer meets one idea rather than three.

import 'package:flutter/material.dart';

import 'package:vsp_mobile/l10n/app_localizations.dart';

/// Marker shown beside a distance derived from unverified coordinates.
class NotSurveyedChip extends StatelessWidget {
  /// Renders as an icon only, for rows too tight for the word.
  final bool iconOnly;

  const NotSurveyedChip({super.key, this.iconOnly = false});

  static const Color _badge = Color(0xFFFBBF24);

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);

    if (iconOnly) {
      return Tooltip(
        message: l10n.distanceNotSurveyedTooltip,
        child: Semantics(
          label: l10n.distanceNotSurveyedTooltip,
          child: const Icon(
            Icons.error_outline,
            size: 14,
            color: _badge,
            semanticLabel: null,
          ),
        ),
      );
    }

    return Semantics(
      label: l10n.distanceNotSurveyedTooltip,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
        decoration: BoxDecoration(
          color: _badge.withOpacity(0.15),
          borderRadius: BorderRadius.circular(4),
          border: Border.all(color: _badge.withOpacity(0.5)),
        ),
        child: Text(
          l10n.holeNoGeometryBadge,
          style: const TextStyle(
            color: _badge,
            fontSize: 10,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
    );
  }
}
