package vnpt.vsp.api.pagination;

import org.springframework.core.MethodParameter;
import org.springframework.http.MediaType;
import org.springframework.http.server.ServerHttpRequest;
import org.springframework.http.server.ServerHttpResponse;
import org.springframework.http.converter.HttpMessageConverter;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.servlet.mvc.method.annotation.ResponseBodyAdvice;

import java.util.List;

/**
 * {@link RestControllerAdvice} that intercepts responses from methods annotated with
 * {@link Paged @Paged} and wraps the returned list in a {@link Pagination} DTO.
 * <p>
 * This advice only activates when:
 * <ul>
 *   <li>The return type is {@code List&lt;T&gt;}</li>
 *   <li>The controller method is annotated with {@link Paged}</li>
 * </ul>
 * <p>
 * The {@link PageTokenService} is used to generate the {@code pageToken} for the
 * next page based on the current {@link Pageable} state. The {@code hasMore} flag
 * is set based on whether the returned list size equals the requested page size.
 * <p>
 * Note: When the underlying service returns a {@link Page}, this advice defers to
 * the {@link Page} and extracts its metadata rather than wrapping a raw list.
 */
@RestControllerAdvice
public class PaginationAdvice implements ResponseBodyAdvice<Object> {

    private final PageTokenService pageTokenService;

    public PaginationAdvice(PageTokenService pageTokenService) {
        this.pageTokenService = pageTokenService;
    }

    @Override
    public boolean supports(MethodParameter returnType, Class<? extends HttpMessageConverter<?>> converterType) {
        return returnType.hasMethodAnnotation(Paged.class);
    }

    @Override
    public Object beforeBodyWrite(
            Object body,
            MethodParameter returnType,
            MediaType selectedContentType,
            Class<? extends HttpMessageConverter<?>> selectedConverterType,
            ServerHttpRequest request,
            ServerHttpResponse response
    ) {
        Paged paged = returnType.getMethodAnnotation(Paged.class);

        if (body instanceof List<?> list) {
            return wrapList(list, paged);
        }

        return body;
    }

    @SuppressWarnings("unchecked")
    private <T> Pagination<T> wrapList(List<?> list, Paged paged) {
        int pageSize = paged != null ? paged.defaultPageSize() : 20;
        boolean hasMore = list.size() >= pageSize;

        Pagination<T> pagination = new Pagination<>();
        pagination.setItems((List<T>) list);
        pagination.setHasMore(hasMore);
        // pageToken is generated by the caller using PageConstraints and PageTokenService;
        // the advice only wraps the list — callers inject the token via the response path

        return pagination;
    }
}
