-- A shot could never name the club it was hit with.
--
-- shots.club_id was uuid; clubs.id is bigint, generated by identity. So
-- `JOIN clubs c ON s.club_id = c.id` — which is what bag performance runs — is
-- not a query that returns nothing, it is a query Postgres refuses:
--
--   ERROR: operator does not exist: uuid = bigint
--
-- Every request to GET /bags/{id}/performance answered 500 with a correlation
-- id, and the screen behind it has never once worked. club_performance got the
-- type right — bigint, with a foreign key to clubs — so the two halves of the
-- same feature disagreed about what a club is.
--
-- SAFE TO CHANGE
--
--   Six shots exist and not one carries a club_id, because none could ever
--   have been written: nothing on either side could produce a uuid that named
--   a club. club_performance is empty for the same reason. There is no data to
--   preserve and none to lose.
--
-- The foreign key is added with the type, so the next thing to write a club id
-- that does not name a club is refused at the point of writing rather than at
-- the point of reading, a release later.

ALTER TABLE shots
    ALTER COLUMN club_id TYPE bigint USING NULL;

ALTER TABLE shots
    ADD CONSTRAINT shots_club_id_fkey
    FOREIGN KEY (club_id) REFERENCES clubs(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_shots_club ON shots (club_id);

COMMENT ON COLUMN shots.club_id IS
    'The club this shot was hit with. bigint to match clubs.id — it was uuid, which made every join against clubs a type error.';
