package vnpt.vsp.api.error;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.Map;
import java.util.Objects;

/**
 * Structured error response DTO emitted by the {@link GlobalExceptionHandler}.
 * <p>
 * Schema (matches OpenAPI {@code ErrorResponse} schema):
 * <pre>
 * {
 *   "code": "VSP-ERR-COURSE-001",
 *   "message": "Course not found",
 *   "correlationId": "a1b2c3d4-...",
 *   "field": "courseId",        // optional, present for field-level errors
 *   "details": { ... }          // optional, present when extra context is needed
 * }
 * </pre>
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ErrorResponse {

    private String code;
    private String message;
    private String correlationId;
    private String field;
    private Map<String, Object> details;

    public ErrorResponse() {
    }

    private ErrorResponse(Builder builder) {
        this.code = builder.code;
        this.message = builder.message;
        this.correlationId = builder.correlationId;
        this.field = builder.field;
        this.details = builder.details;
    }

    /**
     * Builds an {@link ErrorResponse} from a {@link VspApiException}.
     *
     * @param ex            the caught exception
     * @param correlationId the correlation ID extracted or generated by {@link CorrelationIdFilter}
     * @return a new {@link ErrorResponse} matching the exception's error code
     */
    public static ErrorResponse from(VspApiException ex, String correlationId) {
        return builder()
                .code(ex.getErrorCode().getCode())
                .message(ex.getMessage())
                .correlationId(correlationId)
                .field(ex.getField())
                .details(ex.getDetails())
                .build();
    }

    public static Builder builder() {
        return new Builder();
    }

    public String getCode() {
        return code;
    }

    public String getMessage() {
        return message;
    }

    public String getCorrelationId() {
        return correlationId;
    }

    public String getField() {
        return field;
    }

    public Map<String, Object> getDetails() {
        return details;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ErrorResponse that = (ErrorResponse) o;
        return Objects.equals(code, that.code)
                && Objects.equals(message, that.message)
                && Objects.equals(correlationId, that.correlationId)
                && Objects.equals(field, that.field)
                && Objects.equals(details, that.details);
    }

    @Override
    public int hashCode() {
        return Objects.hash(code, message, correlationId, field, details);
    }

    @Override
    public String toString() {
        return "ErrorResponse{code='%s', message='%s', correlationId='%s', field='%s', details=%s}"
                .formatted(code, message, correlationId, field, details);
    }

    public static class Builder {
        private String code;
        private String message;
        private String correlationId;
        private String field;
        private Map<String, Object> details;

        public Builder code(String code) {
            this.code = code;
            return this;
        }

        public Builder message(String message) {
            this.message = message;
            return this;
        }

        public Builder correlationId(String correlationId) {
            this.correlationId = correlationId;
            return this;
        }

        public Builder field(String field) {
            this.field = field;
            return this;
        }

        public Builder details(Map<String, Object> details) {
            this.details = details;
            return this;
        }

        public ErrorResponse build() {
            return new ErrorResponse(this);
        }
    }
}
